### PR TITLE
SAIL-18: RMAs emails not working through Sailthru

### PR DESCRIPTION
**Pull request by giraclion**

### CODE REVIEW

**Comment by brownac** [comment]
@giraclion could you perhaps give some instructions for how to reproduce the issue and QA the fix?

**Comment by giraclion** [comment]
@brownac you will need simply to trigger RMA emails in M2 around 20-30 times in a row and verify that they being sent successfully

**Comment by silverman63** [comment]
Hey all, we realized there is an issue with this approach. 

If the plugin thinks a Sailthru template doesn't exist currently, it will attempt to recreate it in Sailthru. The API call then made is an upsert to the relevant Sailthru template.

This is OK when using the actual Magento email body, but if someone configures custom Sailthru templates for the email, the API would revert the template to a Magento-body template when `saveTemplate()` is called.

**Comment by giraclion** [comment]
Hi Alex,

Yes, and that is something that concerned me too. But it was decided
yesterday to have this mitigation for now. I strongly suggest to do
periodic templates sync with additional low TTL caching - which will
resolve the stability, add durability and not create an issue with
overriding template body.

Regards,
Maksym Saveliev,
Frendino | Manager

Miami, FL
(310) 756-5296 mobile
maks@frendino.com
www.frendino.com

**Pull request merged**
