### PR TITLE
fix api validation and config retrieval for Magento instance with several websites

### PR DESCRIPTION
**Pull request by alexpoletaev**
Fix for the #10 issue

### CODE REVIEW

**Comment by silverman63** [comment]
Hi @alexpoletaev,

Could you confirm your test case for this? I don't believe this is fully resolving the issue.

After implementing this code, I visited Store->Configuration->Sailthru->Setup and saved API key information for a different Sailthru account in a new website within my Magento instance. After saving, I visited Stores->Configuration->Sailthru->Lists, and it still reflected the Lists of the default  site's account (the lists are exclusive to each Sailthru account/credentials). 

I believe this may be an issue regarding whether Magento is sharing a singleton between sites. In that case, the API client wouldn't be reset with the proper credentials. This may also be caused by a tangential bug with the source model loading, but if so will not allow admins to setup the proper Sailthru settings for users/templates.


Will investigate further.

**Comment by alexpoletaev** [comment]
Hello @silverman63
My guess I have a test Sailthru account where I set different customer lists for each site (I tested 'currentcatalog' and 'lillianvernon') and after implementing this code I was able to see these lists (each website had it's own list) in the dropdown under the Stores->Configuration->Sailthru->Lists->Customer Sign-Up Lists. Also this code allows to retrieve proper customer list for specific website during registration on Magento frontend (w/o this fix it always returns the list for the default store, 'null' in our case, because we don't have default config, only per website scope). Another one thing I noticed - once I set API key for the specific website, I see successful API key confirmation for other websites despite the fact these fields are empty for these websites, but this does not cause any inconvenience for us. Let me know if you have any other questions. Thanks.

**Comment by silverman63** [comment]
Hi Alexey, I'm going to merge these changes in as they do solve some scoping issues, but you've brought up a larger issue with multisite regarding different API key sets for separate sites. Will create an issue.

**Comment by silverman63** [comment]
@alexpoletaev merged to Master.

**Comment by alexpoletaev** [comment]
@silverman63 , thank you for your feedback.

**Pull request merged**
